#!/bin/sh
rm rdflib.js

echo "\$rdf = function() {" > rdflib.js

cat util.js uri.js term.js match.js rdfparser.js n3parser.js identity.js query.js sparql.js sparqlUpdate.js jsonparser.js  serialize.js >> rdflib.js

echo "return \$rdf;}()" >> rdflib.js
