tabulator.ns = {};
tabulator.ns.link = tabulator.ns.tab = tabulator.ns.tabont = tabulator.rdf.Namespace("http://www.w3.org/2007/ont/link#");
tabulator.ns.http = tabulator.rdf.Namespace("http://www.w3.org/2007/ont/http#");
tabulator.ns.httph = tabulator.rdf.Namespace("http://www.w3.org/2007/ont/httph#");
tabulator.ns.ical = tabulator.rdf.Namespace("http://www.w3.org/2002/12/cal/icaltzd#");
tabulator.ns.foaf = tabulator.rdf.Namespace("http://xmlns.com/foaf/0.1/");
tabulator.ns.rdf = tabulator.rdf.Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#");
tabulator.ns.rdfs = tabulator.rdf.Namespace("http://www.w3.org/2000/01/rdf-schema#");
tabulator.ns.owl = tabulator.rdf.Namespace("http://www.w3.org/2002/07/owl#");
tabulator.ns.dc = tabulator.rdf.Namespace("http://purl.org/dc/elements/1.1/");
tabulator.ns.rss = tabulator.rdf.Namespace("http://purl.org/rss/1.0/");
tabulator.ns.xsd = tabulator.rdf.Namespace("http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-");
tabulator.ns.contact = tabulator.rdf.Namespace("http://www.w3.org/2000/10/swap/pim/contact#");
tabulator.ns.mo = tabulator.rdf.Namespace("http://purl.org/ontology/mo/");